name: mavenwebapp
services:
  mavenwebapp:
    image: awssandy/maven-web-application:${IMAGE_TAG}
    ports:
    - 9090:8080
    networks:
    - mavenwebappbridge
    restart: always
networks:
  mavenwebappbridge:
    driver: bridge
